### 
POST http://localhost:5000/login 
Content-Type: application/json

{
    "username": "admin", 
    "password": "admin"
}
### 
POST http://localhost:5000/token 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTU3NDIyNTN9.p66PDNu0rnZz9IgKRULTvWgidhCu9J3c64TUhmvsAds"
}